name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build Vue
      run: |
            npm ci
            npm run build
            cd dist
            ln -s index.html 404.html
            git config --global user.email "${{ inputs.gitemail }}"
            git config --global user.name "${{ inputs.gitname }}"
            git init
            git add -A
            git commit -m 'deploy'
            git push -f https://q6q9:${{ secrets.GITHUB_TOKEN }}@github.com/q6q9/$q6q9.git 
      shell: bash
